// Generated by gencpp from file rosmon_msgs/StartStopRequest.msg
// DO NOT EDIT!


#ifndef ROSMON_MSGS_MESSAGE_STARTSTOPREQUEST_H
#define ROSMON_MSGS_MESSAGE_STARTSTOPREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace rosmon_msgs
{
template <class ContainerAllocator>
struct StartStopRequest_
{
  typedef StartStopRequest_<ContainerAllocator> Type;

  StartStopRequest_()
    : node()
    , ns()
    , action(0)  {
    }
  StartStopRequest_(const ContainerAllocator& _alloc)
    : node(_alloc)
    , ns(_alloc)
    , action(0)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _node_type;
  _node_type node;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _ns_type;
  _ns_type ns;

   typedef uint8_t _action_type;
  _action_type action;



  enum {
    START = 1u,
    STOP = 2u,
    RESTART = 3u,
  };


  typedef boost::shared_ptr< ::rosmon_msgs::StartStopRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rosmon_msgs::StartStopRequest_<ContainerAllocator> const> ConstPtr;

}; // struct StartStopRequest_

typedef ::rosmon_msgs::StartStopRequest_<std::allocator<void> > StartStopRequest;

typedef boost::shared_ptr< ::rosmon_msgs::StartStopRequest > StartStopRequestPtr;
typedef boost::shared_ptr< ::rosmon_msgs::StartStopRequest const> StartStopRequestConstPtr;

// constants requiring out of line definition

   

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rosmon_msgs::StartStopRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rosmon_msgs::StartStopRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace rosmon_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'rosmon_msgs': ['/tmp/binarydeb/ros-melodic-rosmon-msgs-2.1.1/msg'], 'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::rosmon_msgs::StartStopRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rosmon_msgs::StartStopRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rosmon_msgs::StartStopRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rosmon_msgs::StartStopRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rosmon_msgs::StartStopRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rosmon_msgs::StartStopRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rosmon_msgs::StartStopRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a95e7883b3762847035c73ffc86de3ea";
  }

  static const char* value(const ::rosmon_msgs::StartStopRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa95e7883b3762847ULL;
  static const uint64_t static_value2 = 0x035c73ffc86de3eaULL;
};

template<class ContainerAllocator>
struct DataType< ::rosmon_msgs::StartStopRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rosmon_msgs/StartStopRequest";
  }

  static const char* value(const ::rosmon_msgs::StartStopRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rosmon_msgs::StartStopRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 START = 1\n"
"uint8 STOP = 2\n"
"uint8 RESTART = 3\n"
"\n"
"string node\n"
"string ns\n"
"uint8 action\n"
;
  }

  static const char* value(const ::rosmon_msgs::StartStopRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rosmon_msgs::StartStopRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.node);
      stream.next(m.ns);
      stream.next(m.action);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct StartStopRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rosmon_msgs::StartStopRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rosmon_msgs::StartStopRequest_<ContainerAllocator>& v)
  {
    s << indent << "node: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.node);
    s << indent << "ns: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.ns);
    s << indent << "action: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.action);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROSMON_MSGS_MESSAGE_STARTSTOPREQUEST_H
